version: "3"
services:
  test:  # 서비스 이름
    image: test:latest  # run할 이미지
    container_name: test  # 컨테이너 이름
    ports:
      - 8887:8888  # 로컬의 8889포트와 컨테이너의 8888포트 연결
    volumes:
      - ./source/:/home/  # 로컬의 source폴더와 home 폴더를 마운트 (컨테이너 안의 home 폴더 내용이 로컬의 source 내용과 같아진다.)
    